name: dabba_crew_home_cook_app
description: A home cook dashboard app for Dabba Crew food delivery service.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: any
  shared_preferences: any
  cupertino_icons: ^1.0.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true